### ISSUE TITLE
what kind of data should i download if i want to reproduce your work?

### ISSUE THREAD

**Issue by zhongqin0820** [gombru/WebVision#1]
hi, i want to reproduce your work. but i can't figure out the instruction.
i see in the web vision challege dataset download page: http://www.vision.ee.ethz.ch/webvision/download.html  there are metadata and resize version and original version. what should i download if i want to reproduce your work?

**Comment by gombru** [comment]
Hi,
I used the resized version of the dataset. The full size version was to heavy, and I don't think it makes a difference. 
I wrote a blog post explaining my participation on the competition: https://gombru.github.io/2017/07/26/webvision_challenge/
Raul

**Comment by zhongqin0820** [comment]
Thank you!
